### PR TITLE
Add queryplans and indexes

### PR DESCRIPTION
**Pull request by YinglunQ**

### CODE REVIEW

**Comment by schristley** [comment]
That's good, I like the idea of a role to save the query plan versus giving readWrite access. The only change I can think of is to make variables for some of the field names, specifically `ir_project_sample_id` and the `[vdj]gene_[gene|family]` fields, as those are named differently in my schema. All the fields based on AIRR field names are good.

**Comment by YinglunQ** [comment]
@schristley for those fields that you have mentioned, do you have any namings for the variables that you prefer?

**Comment by schristley** [comment]
@YinglunQ Not really, but maybe use `ir_` as a prefix. Here is a list of the indexes on my system so you can see the difference. I named most of the additional fields with `ir_` prefix so that I knew they were created specifically for ireceptor and not part of the AIRR data. Unfortunately some of my fields are not named well for historical reasons, I never spent the time to rewrite the whole database just to change them.

```
db.rearrangement.getIndexes()
[
	{
		"v" : 2,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "v1public.rearrangement"
	},
	{
		"v" : 2,
		"key" : {
			"filename_uuid" : 1
		},
		"name" : "filename_uuid_1",
		"ns" : "v1public.rearrangement"
	},
	{
		"v" : 2,
		"key" : {
			"filename_uuid" : 1,
			"productive" : 1
		},
		"name" : "filename_uuid_1_productive_1",
		"ns" : "v1public.rearrangement",
		"background" : true
	},
	{
		"v" : 2,
		"key" : {
			"filename_uuid" : 1,
			"junction_aa_length" : 1
		},
		"name" : "filename_uuid_1_junction_aa_length_1",
		"ns" : "v1public.rearrangement",
		"background" : true
	},
	{
		"v" : 2,
		"key" : {
			"filename_uuid" : 1,
			"ir_vgene_gene" : 1
		},
		"name" : "filename_uuid_1_ir_vgene_gene_1",
		"ns" : "v1public.rearrangement",
		"background" : true
	},
	{
		"v" : 2,
		"key" : {
			"filename_uuid" : 1,
			"ir_dgene_gene" : 1
		},
		"name" : "filename_uuid_1_ir_dgene_gene_1",
		"ns" : "v1public.rearrangement",
		"background" : true
	},
	{
		"v" : 2,
		"key" : {
			"filename_uuid" : 1,
			"ir_jgene_gene" : 1
		},
		"name" : "filename_uuid_1_ir_jgene_gene_1",
		"ns" : "v1public.rearrangement",
		"background" : true
	},
	{
		"v" : 2,
		"key" : {
			"filename_uuid" : 1,
			"ir_vgene_allele" : 1
		},
		"name" : "filename_uuid_1_ir_vgene_allele_1",
		"ns" : "v1public.rearrangement",
		"background" : true
	},
	{
		"v" : 2,
		"key" : {
			"filename_uuid" : 1,
			"ir_dgene_allele" : 1
		},
		"name" : "filename_uuid_1_ir_dgene_allele_1",
		"ns" : "v1public.rearrangement",
		"background" : true
	},
	{
		"v" : 2,
		"key" : {
			"filename_uuid" : 1,
			"ir_jgene_allele" : 1
		},
		"name" : "filename_uuid_1_ir_jgene_allele_1",
		"ns" : "v1public.rearrangement",
		"background" : true
	},
	{
		"v" : 2,
		"key" : {
			"filename_uuid" : 1,
			"ir_vgene_family" : 1
		},
		"name" : "filename_uuid_1_ir_vgene_family_1",
		"ns" : "v1public.rearrangement",
		"background" : true
	},
	{
		"v" : 2,
		"key" : {
			"filename_uuid" : 1,
			"ir_dgene_family" : 1
		},
		"name" : "filename_uuid_1_ir_dgene_family_1",
		"ns" : "v1public.rearrangement",
		"background" : true
	},
	{
		"v" : 2,
		"key" : {
			"filename_uuid" : 1,
			"ir_jgene_family" : 1
		},
		"name" : "filename_uuid_1_ir_jgene_family_1",
		"ns" : "v1public.rearrangement",
		"background" : true
	},
	{
		"v" : 2,
		"key" : {
			"filename_uuid" : 1,
			"ir_cdr3_substrings" : 1
		},
		"name" : "filename_uuid_1_ir_cdr3_substrings_1",
		"ns" : "v1public.rearrangement"
	},
	{
		"v" : 2,
		"key" : {
			"filename_uuid" : 1,
			"ir_cdr3_suffix" : 1
		},
		"name" : "filename_uuid_1_ir_cdr3_suffix_1",
		"ns" : "v1public.rearrangement"
	}
]

```

**Review by bcorrie — DISMISSED** [review]
Hi Colin, looks good... You can merge the pull request if you like (assuming you are allowed to?).

We can do performance testing to make sure the indexes and the query plans are working after we add the Wang data.

**Comment by YinglunQ** [comment]
@bcorrie seems like i do not have the permission to merge pull request :)

**Review by bcorrie — APPROVED** [review]
Thumbs up 8-)

**Comment by bcorrie** [comment]
@YinglunQ merge done...

**Pull request merged**
